---
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Restart application
  systemd:
    name: "{{ app_name }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
  when: use_system_d

- name: me
  debug:
    msg: 'I have been notified'
