---
- name: set_fact
  set_fact:
      user : "{{ username }}"
      uid : "{{ uid }}"
      group : "{{ groupname }}"
      passwd : "{{ userpasswd }}"

- name: Manage user
  user:
    name: "{{ username }}"
    uid: "{{ uid }}"
    password: "{{ userpasswd }}"
    group: "{{ groupname }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    system: true
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
