---
- hosts: all
  gather_facts: false
  tasks:
    - name: my appender
      ansible.builtin.set_fact:
        PACKAGES: '{{PACKAGES_HOST | default ([]) + PACKAGES_GROUP | default ([]) + PACKAGES_BACK | default ([]) + PACKAGES_COMMON}}'
    - name: debug
      ansible.builtin.debug:
        var: PACKAGES, VARIABLE
