---
- name: concat
  set_fact:
    appName : "{{ app_name | default('') }}"
    srcFile : "{{ springboot_src_file | default('') }}"
    deployFolder : "{{ springboot_deploy_folder | default('') }}"
    propertiesTpl : "{{ springboot_propertyfile_template | default('') }}"
    confTpl : "{{ springboot_configuration_template | default('') }}"

- name: debug
  debug:
    var: appName,srcFile,deployFolder,propertiesTpl,confTpl 

- name: "Check for required inventory app_name variable"
  fail:
    msg: app_name variable is required and should be defined in you inventory
  when: not app_name

- name: "Check for required inventory springboot_src_file or springboot_src_url variable"
  fail:
    msg: springboot_src variable or springboot_src_url is required and should be defined in you inventory
  when: (not springboot_src_file) and (not springboot_src_url)

- name: "Create deploy folder if not exists"
  file:
    path: "{{ springboot_deploy_folder }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ groupname }}"

- name: "Copy jar application"
  copy:
    src: "{{ springboot_src_file }}"
    dest: "{{ springboot_deploy_folder }}/{{ app_name }}.jar"
    owner: "{{ username }}"
    group: "{{ groupname }}"
    mode: "u+x"
  when: springboot_src_file is defined and springboot_src_file|length > 0
  notify:
    - "Restart application"

- name: "Download springboot application"
  get_url:
    url: "{{ springboot_src_url }}"
    dest: "{{ springboot_deploy_folder }}/{{ app_name }}.jar"
    owner: "{{ groupname }}"
    group: "{{ groupname }}"
    mode: "u+x"
  when: springboot_src_url is defined and springboot_src_url|length > 0
  notify:
    - "Restart application"

- name: "Deploy app properties"
  template:
    src: "{{ springboot_propertyfile_template }}"
    dest: "{{ springboot_deploy_folder }}"
    owner: "{{ groupname }}"
    group: "{{ groupname }}"
  when: springboot_propertyfile_template is defined and springboot_propertyfile_template|length > 0
  notify:
    - "Restart application"

- name: "Deploy app config"
  template:
    src: "{{ springboot_configuration_template }}"
    dest: "{{ springboot_deploy_folder }}"
    owner: "{{ groupname }}"
    group: "{{ groupname }}"
  when: springboot_configuration_template is defined and springboot_configuration_template|length > 0
  notify:
    - "Restart application"

- name: Install as service
  include_tasks: service.yml