---
- name: set_fact
  set_fact:
      group : "{{ groupname }}"
      gid : "{{ gid }}"

- name: Manage group with correct gid
  group:
    name: "{{ group }}"
    state: present
    gid: "{{ gid }}"
    